global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'mcp-server'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - mcp-prod
            - mcp-staging
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: mcp-server
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: 9090
        action: keep

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true